// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `
{
	"schemes": {{ marshal .Schemes }},
	"swagger": "2.0",
	"info": {
		"title": "{{.Title}}",
		"version": "{{.Version}}",
		"description": "{{escape .Description}}"
	},
	"host": "{{.Host}}",
	"basePath": "{{.BasePath}}",
	"tags": [
		{
			"name": "Auth",
			"description": "Authentication management"
		},
		{
			"name": "Category",
			"description": "Category management"
		},
		{
			"name": "News",
			"description": "News management"
		},
		{
			"name": "Comment",
			"description": "Comment management"
		},
		{
			"name": "Page",
			"description": "Page management"
		}
	],
	"components": {
		"securitySchemes": {
			"BearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	},
	"paths": {
		"/api/auth/login": {
			"post": {
				"summary": "Login to existing account",
				"tags": ["Auth"],
				"parameters": [
					{
						"name": "username",
						"in": "body",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "password",
						"in": "body",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Login successful",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"access_token": {
											"type": "string"
										},
										"expires_in": {
											"type": "number"
										},
										"token_type": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "Invalid email or password",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}			
					},
					"500": {
						"description": "Error logging in",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/categories": {
			"get": {
				"summary": "Get all categories",
				"tags": ["Category"],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get all categories",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"id": {
												"type": "string"
											},
											"name": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Categories not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error getting categories",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"post": {
				"summary": "Create new category",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "category",
						"in": "body",
						"required": true,
						"schema": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Category created",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error creating category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/categories/{id}": {
			"get": {
				"summary": "Get category by id",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get category by id",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Category not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error getting category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"put": {
				"summary": "Update category by id",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					},
					{
						"name": "category",
						"in": "body",
						"required": true,
						"schema": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Category updated",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					}
				}
			},
			"delete": {
				"summary": "Delete category by id",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Category deleted",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object"
								}
							}
						}
					},
					"404": {
						"description": "Category not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error deleting category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		}
	}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Content Management System",
	Description:      "A simple content management system API for managing news",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
