// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `
{
	"schemes": {{ marshal .Schemes }},
	"swagger": "2.0",
	"info": {
		"title": "{{.Title}}",
		"version": "{{.Version}}",
		"description": "{{escape .Description}}"
	},
	"host": "{{.Host}}",
	"basePath": "{{.BasePath}}",
	"tags": [
		{
			"name": "Auth",
			"description": "Authentication management"
		},
		{
			"name": "Category",
			"description": "Category management"
		},
		{
			"name": "News",
			"description": "News management"
		},
		{
			"name": "Comment",
			"description": "Comment management"
		},
		{
			"name": "Page",
			"description": "Page management"
		}
	],
	"components": {
		"securitySchemes": {
			"BearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	},
	"paths": {
		"/api/auth/login": {
			"post": {
				"summary": "Login to existing account",
				"tags": ["Auth"],
				"parameters": [
					{
						"name": "login",
						"in": "body",
						"required": true,
						"schema": {
							"type": "object",
							"properties": {
								"username": {
									"type": "string"
								},
								"password": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Login successful",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"access_token": {
											"type": "string"
										},
										"expires_in": {
											"type": "number"
										},
										"token_type": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "Invalid email or password",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}			
					},
					"500": {
						"description": "Error logging in",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/categories": {
			"get": {
				"summary": "Get all categories",
				"tags": ["Category"],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get all categories",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"id": {
												"type": "string"
											},
											"name": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Categories not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error getting categories",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"post": {
				"summary": "Create new category",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "category",
						"in": "body",
						"required": true,
						"schema": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"201": {
						"description": "Category created",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"500": {
						"description": "Error creating category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/categories/{id}": {
			"get": {
				"summary": "Get category by id",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get category by id",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "Category not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error getting category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"put": {
				"summary": "Update category by id",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					},
					{
						"name": "category",
						"in": "body",
						"required": true,
						"schema": {
							"type": "object",
							"properties": {
								"name": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Category updated",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"name": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"404": {
						"description": "Category not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error updating category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"delete": {
				"summary": "Delete category by id",
				"tags": ["Category"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Category deleted",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object"
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"404": {
						"description": "Category not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error deleting category",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/news": {
			"get": {
				"summary": "Get all news",
				"tags": ["News"],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get all news",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"id": {
												"type": "string"
											},
											"title": {
												"type": "string"
											},
											"content": {
												"type": "string"
											},
											"user": {
												"type": "object",
												"properties": {
													"name": {
														"type": "string"
													}
												}
											},
											"category": {
												"type": "object",
												"properties": {
													"name": {
														"type": "string"
													}
												}
											},
											"created_at": {
												"type": "string"
											},
											"updated_at": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "News not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error getting news",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"post": {
				"summary": "Create new news",
				"tags": ["News"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "news",
						"in": "body",
						"required": true,
						"type": "object",
						"schema": {
							"type": "object",
							"properties": {
								"title": {
									"type": "string"
								},
								"content": {
									"type": "string"
								},
								"category_id": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"201": {
						"description": "news created successfully",
						"schema": {
							"type": "object",
							"properties": {
								"message": {
									"type": "string"
								}
							}
						}
					},
					"400": {
						"description": "invalid request body",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "error creating news",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/news/{id}": {
			"get": {
				"summary": "Get news by id",
				"tags": ["News"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get news by id",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"title": {
											"type": "string"
										},
										"content": {
											"type": "string"
										},
										"user": {
											"type": "object",
											"properties": {
												"name": {
													"type": "string"
												}
											}
										},
										"category": {
											"type": "object",
											"properties": {
												"name": {
													"type": "string"
												}
											}
										},
										"created_at": {
											"type": "string"
										},
										"updated_at": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "News not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "Error getting news",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"put": {
				"summary": "Update news by id",
				"tags": ["News"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					},
					{
						"name": "news",
						"in": "body",
						"required": true,
						"type": "object",
						"schema": {
							"type": "object",
							"properties": {
								"title": {
									"type": "string"
								},
								"content": {
									"type": "string"
								},
								"category_id": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "news updated successfully",
						"schema": {
							"type": "object",
							"properties": {
								"message": {
									"type": "string"
								}
							}
						}
					},
					"400": {
						"description": "invalid request body",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"500": {
						"description": "error updating news",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					}
				}
			},
			"delete": {
				"summary": "Delete news by id",
				"tags": ["News"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					},
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "news deleted successfully",
						"schema": {
							"type": "object",
							"properties": {
								"message": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"404": {
						"description": "news not found",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"500": {
						"description": "error deleting news",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"/api/news/{id}/comments": {
			"get": {
				"summary": "Get comments by news id",
				"tags": ["Comment"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get comments by news id",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"id": {
												"type": "string"
											},
											"name": {
												"type": "string"
											},
											"comment": {
												"type": "string"
											},
											"created_at": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "invalid request body",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "error getting comments",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}							
						}
					}
				}
			},
			"post": {
				"summary": "Create comment",
				"tags": ["Comment"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "comment",
						"in": "body",
						"required": true,
						"type": "object",
						"schema": {
							"type": "object",
							"properties": {
								"comment": {
									"type": "string"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"201": {
						"description": "comment created successfully",
						"schema": {
							"type": "object",
							"properties": {
								"message": {
									"type": "string"
								}
							}
						}
					},
					"400": {
						"description": "invalid request body",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "error creating comment",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
		"/api/pages": {
			"get": {
				"summary": "Get all pages",
				"tags": ["Page"],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get all pages",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"id": {
												"type": "string"
											},
											"title": {
												"type": "string"
											},
											"custom_url": {
												"type": "string"
											},
											"content": {
												"type": "string"
											},
											"is_published": {
												"type": "boolean"
											},
											"user": {
												"type": "object",
												"properties": {
													"name": {
														"type": "string"
													}
												}
											},
											"created_at": {
												"type": "string"
											},
											"updated_at": {
												"type": "string"
											}
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "error getting pages",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"post": {
				"summary": "Create new page",
				"tags": ["Page"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "page",
						"in": "body",
						"required": true,
						"type": "object",
						"schema": {
							"type": "object",
							"properties": {
								"title": {
									"type": "string"
								},
								"custom_url": {
									"type": "string"
								},
								"content": {
									"type": "string"
								},
								"is_published": {
									"type": "boolean"
								}
							}
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"201": {
						"description": "page created successfully",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "invalid request body",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"500": {
						"description": "error creating page",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					}
				}
			}
		},
		"/api/pages/{id}": {
			"get": {
				"summary": "Get page by id",
				"tags": ["Page"],
				"parameters": [
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Get page by id",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string"
										},
										"title": {
											"type": "string"
										},
										"custom_url": {
											"type": "string"
										},
										"content": {
											"type": "string"
										},
										"is_published": {
											"type": "boolean"
										},
										"user": {
											"type": "object",
											"properties": {
												"name": {
													"type": "string"
												}
											}
										},
										"created_at": {
											"type": "string"
										},
										"updated_at": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"404": {
						"description": "not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "error getting page",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			},
			"put": {
				"summary": "Update page by id",
				"tags": ["Page"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "id",
						"in": "path",
						"required": true,
						"type": "string"
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "page updated successfully",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "invalid request body",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"404": {
						"description": "not found",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"500": {
						"description": "error updating page",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					}
				}
			},
			"delete": {
				"summary": "Delete page by id",
				"tags": ["Page"],
				"parameters": [
					{
						"name": "Authorization",
						"in": "header",
						"required": true,
						"type": "string"
					},
					{
						"name": "id",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "page deleted successfully",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"message": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "unauthorized",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"404": {
						"description": "not found",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					},
					"500": {
						"description": "error deleting page",
						"schema": {
							"type": "object",
						},
						"properties": {
							"error": {
								"type": "string"
							}
						}
					}
				}
			}
		}
	}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Content Management System",
	Description:      "A simple content management system API for managing news",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
