// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `
{
	"schemes": {{ marshal .Schemes }},
	"swagger": "2.0",
	"info": {
		"title": "{{.Title}}",
		"version": "{{.Version}}",
		"description": "{{escape .Description}}",
	},
	"host": "{{.Host}}",
	"basePath": "{{.BasePath}}",
	"tags": [
		{
			"name": "Auth",
			"description": "Authentication management"
		},
	],
	"components": {
		"securitySchemes": {
			"BearerAuth": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT"
			}
		}
	},
	"paths": {
		"/api/auth/login": {
			"post": {
				"summary": "Login to existing account",
				"tags": ["Auth"],
				"parameters": [
					{
						"name": "email",
						"in": "body",
						"required": true,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "password",
						"in": "body",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"produces": [
					"application/json"
				],
				"responses": {
					"200": {
						"description": "Login successful",
						"schema": {
							"type": "object",
							"properties": {
								"data": {
									"type": "object",
									"properties": {
										"access_token": {
											"type": "string"
										},
										"expires_in": {
											"type": "number"
										},
										"token_type": {
											"type": "string"
										}
									}
								}
							}
						}
					},
					"400": {
						"description": "Bad request",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					},
					"401": {
						"description": "Invalid email or password",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}			
					},
					"500": {
						"description": "Error logging in",
						"schema": {
							"type": "object",
							"properties": {
								"error": {
									"type": "string"
								}
							}
						}
					}
				}
			}
		},
	}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.2.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Content Management System",
	Description:      "A simple content management system API for managing news",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
